services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - 27017:27017
    networks:
      - local_app_network
    volumes:
      - ./mongo_data:/data/db
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  mongo_data:

networks:
  local_app_network:
    external: true
