name: PostgreSQL healthcheck

on:
  # For testing
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    container:
      image: postgres:alpine
    timeout-minutes: 5
    steps:
      - name: Ping Aiven PostgreSQL
        env:
          PGHOST: ${{ secrets.DB_HOST }}
          PGPORT: ${{ secrets.DB_PORT }}
          PGDATABASE: ${{ secrets.DB_NAME }}
          PGUSER: ${{ secrets.DB_USER }}
          PGPASSWORD: ${{ secrets.DB_PASS }}
          PGSSLMODE: require
          PGCONNECT_TIMEOUT: 15
        run: psql -X -v ON_ERROR_STOP=1 -c 'SELECT 1;'